### ISSUE TITLE
Why not just use the mortgage model all the time?

### ISSUE THREAD

**Issue by RobbieTheWagner** [axiommike/smart-app#23]
Seems like extra work to switch between an applicant and mortgage model. Couldn't we just use the mortgage model all the time, and just make the unused fields `null`?

**Comment by axiommike** [comment]
The database is person centric. If there is limited info then no need to create a mortgage just create a person. I'm open to looking at it in the interest of time though.

**Comment by axiommike** [comment]
Also we would still need to derive persons(applicants) from mortgage as it is many to many relationship

**Comment by RobbieTheWagner** [comment]
@axiommike what about the case where you fill out another page or two and then "submit as is"? Should that pull the first `applicant` out of the mortgage model to use for the `thank-you` page? 

I definitely understand the need to keep the people separate in the database, but just trying to ensure we get the flow right and use the correct models in the correct places.

**Comment by ericmaicon** [comment]
I am wondering that you are talking about index.js page? The first one, right!? I am asking this because person model is only used there. The flow should be:

1. First page, person model. 
2. Click in "Contact Now"? Send the person page and use it in thank you page
3. Click in "Complete Full Application"? Create the mortgage, put person as applicant and use it there. After that, you can always use the mortgage model.

So, the answer of your question is: 
> Should that pull the first applicant out of the mortgage model to use for the thank-you page?

You should save the mortgage (hit the mortgage api). It should save everything (even the applicants). Also, there isn't submit as is in the first page, so, I think that you will have the mortgage model.

Let me know if you have further questions.

**Comment by RobbieTheWagner** [comment]
@ericmaicon you can have multiple applicants in a mortgage though, so I am just asking what name to display on thank-you page.

I am currently just taking the first applicant out of the applicants array. I think this should work fine.

**Comment by ericmaicon** [comment]
yep, the first one is the one.
